POWER_BASE = 2 # Used to measure the difficulty of monsters of different difficulty: 20% more stats
ATTACK_HEURISTIC = 1 # Used to gauge how useful attack is as a stat
DEFENSE_HEURISTIC = 1 # Used to gauge how useful defense is as a stat
HEALTH_HEURISTIC = 0.2 # Used to gauge how useful health is as a stat
SPEED_HEURISTIC = 5 # Used to gauge how useful speed is as a stat
MAGIC_HEURISTIC = 0.5  # Used to gauge how useful magic is as a stat
RESIST_HEURISTIC = 0.5 # Used to gauge how useful resist is as a stat
LEVEL_CONSTANT = 0.2 # affects the how people level up
POINTS_PER_LEVEL = 10 # Amount of points distributed to stats per level up
DAMAGE_VARIATION = 20 # Variation of damage
HEAL_VARIATION = 20 # Variation of healing
MAX_LEVEL = 15 # Maximum level that each player can have
EXPERIENCE_PER_BATTLE = 30 # Experience per battle