# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.monster_tab = QtWidgets.QWidget()
        self.monster_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.monster_tab.setObjectName("monster_tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.monster_tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.monster_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_3.addWidget(self.graphicsView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_2 = QtWidgets.QListWidget(self.monster_tab)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout.addWidget(self.listWidget_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.monster_tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.monster_tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(24)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_7.addWidget(self.listWidget_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_7.addWidget(self.pushButton_4)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listView_2 = QtWidgets.QListView(self.groupBox_3)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_4.addWidget(self.listView_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.monster_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_5.addWidget(self.listWidget)
        self.pushButton = QtWidgets.QPushButton(self.monster_tab)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.monster_tab, "")
        self.scenario_tab = QtWidgets.QWidget()
        self.scenario_tab.setObjectName("scenario_tab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.scenario_tab)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scenario_tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_10.addWidget(self.lineEdit_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.comboBox_3 = QtWidgets.QComboBox(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_11.addWidget(self.comboBox_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.comboBox_4 = QtWidgets.QComboBox(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_12.addWidget(self.comboBox_4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.treeWidget = QtWidgets.QTreeWidget(self.scenario_tab)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_12.addWidget(self.treeWidget)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.listWidget_5 = QtWidgets.QListWidget(self.scenario_tab)
        self.listWidget_5.setObjectName("listWidget_5")
        self.verticalLayout_13.addWidget(self.listWidget_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.scenario_tab)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_13.addWidget(self.pushButton_6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.scenario_tab, "")
        self.item_tab = QtWidgets.QWidget()
        self.item_tab.setObjectName("item_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.item_tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.item_tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_9.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_9.addWidget(self.radioButton_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_7.addWidget(self.comboBox_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.item_status = QtWidgets.QTableWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_status.sizePolicy().hasHeightForWidth())
        self.item_status.setSizePolicy(sizePolicy)
        self.item_status.setGridStyle(QtCore.Qt.SolidLine)
        self.item_status.setObjectName("item_status")
        self.item_status.setColumnCount(1)
        self.item_status.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.item_status.setItem(6, 0, item)
        self.item_status.horizontalHeader().setVisible(False)
        self.item_status.horizontalHeader().setCascadingSectionResizes(True)
        self.item_status.horizontalHeader().setHighlightSections(False)
        self.item_status.horizontalHeader().setSortIndicatorShown(False)
        self.item_status.horizontalHeader().setStretchLastSection(True)
        self.item_status.verticalHeader().setVisible(True)
        self.item_status.verticalHeader().setCascadingSectionResizes(False)
        self.item_status.verticalHeader().setDefaultSectionSize(24)
        self.item_status.verticalHeader().setHighlightSections(True)
        self.item_status.verticalHeader().setSortIndicatorShown(True)
        self.item_status.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_10.addWidget(self.item_status)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.listWidget_4 = QtWidgets.QListWidget(self.groupBox_8)
        self.listWidget_4.setObjectName("listWidget_4")
        self.verticalLayout_11.addWidget(self.listWidget_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_11.addWidget(self.pushButton_5)
        self.horizontalLayout_8.addWidget(self.groupBox_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.item_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionAdd_Floor_Type = QtWidgets.QAction(MainWindow)
        self.actionAdd_Floor_Type.setObjectName("actionAdd_Floor_Type")
        self.actionAdd_Item = QtWidgets.QAction(MainWindow)
        self.actionAdd_Item.setObjectName("actionAdd_Item")
        self.actionAdd_Skill = QtWidgets.QAction(MainWindow)
        self.actionAdd_Skill.setObjectName("actionAdd_Skill")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAdd_Attribute = QtWidgets.QAction(MainWindow)
        self.actionAdd_Attribute.setObjectName("actionAdd_Attribute")
        self.actionAdd_Effect = QtWidgets.QAction(MainWindow)
        self.actionAdd_Effect.setObjectName("actionAdd_Effect")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAdd_Floor_Type)
        self.menuEdit.addAction(self.actionAdd_Item)
        self.menuEdit.addAction(self.actionAdd_Skill)
        self.menuEdit.addAction(self.actionAdd_Attribute)
        self.menuEdit.addAction(self.actionAdd_Effect)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RPG Editor"))
        self.pushButton_3.setText(_translate("MainWindow", "Add New Drop..."))
        self.groupBox.setTitle(_translate("MainWindow", "Monster"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Location"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Stats"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Attack"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Speed"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Defense"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Health"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Magic"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resist"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("MainWindow", "Effects"))
        self.pushButton_4.setText(_translate("MainWindow", "Add New Effect..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Abilities"))
        self.pushButton_2.setText(_translate("MainWindow", "Add New Ability..."))
        self.pushButton.setText(_translate("MainWindow", "Create New Monster..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.monster_tab), _translate("MainWindow", "Monster"))
        self.label_5.setText(_translate("MainWindow", "Name"))
        self.label_6.setText(_translate("MainWindow", "Location"))
        self.label_7.setText(_translate("MainWindow", "Room Type"))
        self.pushButton_6.setText(_translate("MainWindow", "Add New Scenario..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scenario_tab), _translate("MainWindow", "Scenario"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Item"))
        self.radioButton.setText(_translate("MainWindow", "Base Item"))
        self.radioButton_2.setText(_translate("MainWindow", "Static Item"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Location"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Stats"))
        item = self.item_status.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Attack"))
        item = self.item_status.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Speed"))
        item = self.item_status.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Defense"))
        item = self.item_status.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Health"))
        item = self.item_status.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Magic"))
        item = self.item_status.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resist"))
        item = self.item_status.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Action"))
        item = self.item_status.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.item_status.isSortingEnabled()
        self.item_status.setSortingEnabled(False)
        item = self.item_status.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.item_status.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.item_status.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.item_status.item(3, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.item_status.item(4, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.item_status.item(5, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.item_status.item(6, 0)
        item.setText(_translate("MainWindow", "0"))
        self.item_status.setSortingEnabled(__sortingEnabled)
        self.groupBox_8.setTitle(_translate("MainWindow", "Effects"))
        self.pushButton_5.setText(_translate("MainWindow", "Add New Effect..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.item_tab), _translate("MainWindow", "Item"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAdd_Floor_Type.setText(_translate("MainWindow", "Add Floor Type..."))
        self.actionAdd_Item.setText(_translate("MainWindow", "Add Item..."))
        self.actionAdd_Skill.setText(_translate("MainWindow", "Add Skill..."))
        self.actionQuit.setText(_translate("MainWindow", "Update"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAdd_Attribute.setText(_translate("MainWindow", "Add Attribute..."))
        self.actionAdd_Effect.setText(_translate("MainWindow", "Add Effect..."))

