# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ericzhang/Documents/GitHub/rpeg/editor/scripts/../ui/editor.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.monster_tab = QtWidgets.QWidget()
        self.monster_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.monster_tab.setObjectName("monster_tab")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.monster_tab)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.monsterLayout = QtWidgets.QVBoxLayout()
        self.monsterLayout.setObjectName("monsterLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.monster_tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.monsterImage = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monsterImage.sizePolicy().hasHeightForWidth())
        self.monsterImage.setSizePolicy(sizePolicy)
        self.monsterImage.setMinimumSize(QtCore.QSize(220, 220))
        self.monsterImage.setText("")
        self.monsterImage.setFlat(True)
        self.monsterImage.setObjectName("monsterImage")
        self.horizontalLayout_21.addWidget(self.monsterImage)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.monsterDropList = QtWidgets.QListWidget(self.monster_tab)
        self.monsterDropList.setObjectName("monsterDropList")
        self.verticalLayout.addWidget(self.monsterDropList)
        self.newDrop = QtWidgets.QPushButton(self.monster_tab)
        self.newDrop.setObjectName("newDrop")
        self.verticalLayout.addWidget(self.newDrop)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.monsterLayout.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.monster_tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.monsterName = QtWidgets.QLineEdit(self.groupBox)
        self.monsterName.setObjectName("monsterName")
        self.horizontalLayout.addWidget(self.monsterName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.monsterRating = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monsterRating.sizePolicy().hasHeightForWidth())
        self.monsterRating.setSizePolicy(sizePolicy)
        self.monsterRating.setObjectName("monsterRating")
        self.horizontalLayout_3.addWidget(self.monsterRating)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.monsterFloor = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monsterFloor.sizePolicy().hasHeightForWidth())
        self.monsterFloor.setSizePolicy(sizePolicy)
        self.monsterFloor.setObjectName("monsterFloor")
        self.horizontalLayout_2.addWidget(self.monsterFloor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.monsterStats = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monsterStats.sizePolicy().hasHeightForWidth())
        self.monsterStats.setSizePolicy(sizePolicy)
        self.monsterStats.setGridStyle(QtCore.Qt.SolidLine)
        self.monsterStats.setObjectName("monsterStats")
        self.monsterStats.setColumnCount(1)
        self.monsterStats.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsterStats.setItem(5, 0, item)
        self.monsterStats.horizontalHeader().setVisible(False)
        self.monsterStats.horizontalHeader().setCascadingSectionResizes(True)
        self.monsterStats.horizontalHeader().setHighlightSections(False)
        self.monsterStats.horizontalHeader().setSortIndicatorShown(False)
        self.monsterStats.horizontalHeader().setStretchLastSection(True)
        self.monsterStats.verticalHeader().setVisible(False)
        self.monsterStats.verticalHeader().setCascadingSectionResizes(False)
        self.monsterStats.verticalHeader().setDefaultSectionSize(24)
        self.monsterStats.verticalHeader().setHighlightSections(True)
        self.monsterStats.verticalHeader().setSortIndicatorShown(True)
        self.monsterStats.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.monsterStats)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.monsterAttrList = QtWidgets.QListWidget(self.groupBox_4)
        self.monsterAttrList.setObjectName("monsterAttrList")
        self.verticalLayout_7.addWidget(self.monsterAttrList)
        self.newAttribute = QtWidgets.QPushButton(self.groupBox_4)
        self.newAttribute.setObjectName("newAttribute")
        self.verticalLayout_7.addWidget(self.newAttribute)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.monsterAbilityList = QtWidgets.QListWidget(self.groupBox_3)
        self.monsterAbilityList.setObjectName("monsterAbilityList")
        self.verticalLayout_4.addWidget(self.monsterAbilityList)
        self.newAbility = QtWidgets.QPushButton(self.groupBox_3)
        self.newAbility.setObjectName("newAbility")
        self.verticalLayout_4.addWidget(self.newAbility)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.monsterLayout.addWidget(self.groupBox)
        self.horizontalLayout_23.addLayout(self.monsterLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.monsterList = QtWidgets.QListWidget(self.monster_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monsterList.sizePolicy().hasHeightForWidth())
        self.monsterList.setSizePolicy(sizePolicy)
        self.monsterList.setObjectName("monsterList")
        self.verticalLayout_5.addWidget(self.monsterList)
        self.newMonster = QtWidgets.QPushButton(self.monster_tab)
        self.newMonster.setObjectName("newMonster")
        self.verticalLayout_5.addWidget(self.newMonster)
        self.horizontalLayout_23.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.monster_tab, "")
        self.scenario_tab = QtWidgets.QWidget()
        self.scenario_tab.setObjectName("scenario_tab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.scenario_tab)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.dialogueLayout = QtWidgets.QVBoxLayout()
        self.dialogueLayout.setObjectName("dialogueLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.eventName = QtWidgets.QLineEdit(self.scenario_tab)
        self.eventName.setObjectName("eventName")
        self.horizontalLayout_10.addWidget(self.eventName)
        self.dialogueLayout.addLayout(self.horizontalLayout_10)
        self.dialogues = QtWidgets.QTreeWidget(self.scenario_tab)
        self.dialogues.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.dialogues.setExpandsOnDoubleClick(True)
        self.dialogues.setObjectName("dialogues")
        self.dialogueLayout.addWidget(self.dialogues)
        self.newDialogue = QtWidgets.QPushButton(self.scenario_tab)
        self.newDialogue.setObjectName("newDialogue")
        self.dialogueLayout.addWidget(self.newDialogue)
        self.horizontalLayout_13.addLayout(self.dialogueLayout)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.events = QtWidgets.QTreeWidget(self.scenario_tab)
        self.events.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.events.setExpandsOnDoubleClick(False)
        self.events.setObjectName("events")
        self.verticalLayout_13.addWidget(self.events)
        self.newEvent = QtWidgets.QPushButton(self.scenario_tab)
        self.newEvent.setObjectName("newEvent")
        self.verticalLayout_13.addWidget(self.newEvent)
        self.horizontalLayout_13.addLayout(self.verticalLayout_13)
        self.horizontalLayout_13.setStretch(0, 1)
        self.tabWidget.addTab(self.scenario_tab, "")
        self.item_tab = QtWidgets.QWidget()
        self.item_tab.setObjectName("item_tab")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.item_tab)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.itemBox = QtWidgets.QVBoxLayout()
        self.itemBox.setObjectName("itemBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.itemBase = QtWidgets.QHBoxLayout()
        self.itemBase.setObjectName("itemBase")
        self.base = QtWidgets.QRadioButton(self.item_tab)
        self.base.setChecked(True)
        self.base.setObjectName("base")
        self.itemBase.addWidget(self.base)
        self.nonbase = QtWidgets.QRadioButton(self.item_tab)
        self.nonbase.setObjectName("nonbase")
        self.itemBase.addWidget(self.nonbase)
        self.verticalLayout_8.addLayout(self.itemBase)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.item_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.itemName = QtWidgets.QLineEdit(self.item_tab)
        self.itemName.setObjectName("itemName")
        self.horizontalLayout_6.addWidget(self.itemName)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.item_tab)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        self.itemType = QtWidgets.QComboBox(self.item_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemType.sizePolicy().hasHeightForWidth())
        self.itemType.setSizePolicy(sizePolicy)
        self.itemType.setObjectName("itemType")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.horizontalLayout_15.addWidget(self.itemType)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.item_tab)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.itemSlot = QtWidgets.QComboBox(self.item_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemSlot.sizePolicy().hasHeightForWidth())
        self.itemSlot.setSizePolicy(sizePolicy)
        self.itemSlot.setObjectName("itemSlot")
        self.itemSlot.addItem("")
        self.itemSlot.addItem("")
        self.itemSlot.addItem("")
        self.itemSlot.addItem("")
        self.itemSlot.addItem("")
        self.itemSlot.addItem("")
        self.horizontalLayout_14.addWidget(self.itemSlot)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.itemBox.addLayout(self.verticalLayout_8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.item_tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.itemStats = QtWidgets.QTableWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemStats.sizePolicy().hasHeightForWidth())
        self.itemStats.setSizePolicy(sizePolicy)
        self.itemStats.setGridStyle(QtCore.Qt.SolidLine)
        self.itemStats.setObjectName("itemStats")
        self.itemStats.setColumnCount(1)
        self.itemStats.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(6, 0, item)
        self.itemStats.horizontalHeader().setVisible(False)
        self.itemStats.horizontalHeader().setCascadingSectionResizes(True)
        self.itemStats.horizontalHeader().setHighlightSections(False)
        self.itemStats.horizontalHeader().setSortIndicatorShown(False)
        self.itemStats.horizontalHeader().setStretchLastSection(True)
        self.itemStats.verticalHeader().setVisible(False)
        self.itemStats.verticalHeader().setCascadingSectionResizes(False)
        self.itemStats.verticalHeader().setDefaultSectionSize(24)
        self.itemStats.verticalHeader().setHighlightSections(True)
        self.itemStats.verticalHeader().setSortIndicatorShown(True)
        self.itemStats.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_10.addWidget(self.itemStats)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.item_tab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.attrList = QtWidgets.QListWidget(self.groupBox_8)
        self.attrList.setObjectName("attrList")
        self.verticalLayout_11.addWidget(self.attrList)
        self.attrButton = QtWidgets.QPushButton(self.groupBox_8)
        self.attrButton.setObjectName("attrButton")
        self.verticalLayout_11.addWidget(self.attrButton)
        self.horizontalLayout_8.addWidget(self.groupBox_8)
        self.itemBox.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_22.addLayout(self.itemBox)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.itemList = QtWidgets.QListWidget(self.item_tab)
        self.itemList.setObjectName("itemList")
        self.verticalLayout_22.addWidget(self.itemList)
        self.pushButton_6 = QtWidgets.QPushButton(self.item_tab)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_22.addWidget(self.pushButton_6)
        self.horizontalLayout_22.addLayout(self.verticalLayout_22)
        self.tabWidget.addTab(self.item_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.moveLayout = QtWidgets.QVBoxLayout()
        self.moveLayout.setObjectName("moveLayout")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.moveIcon = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveIcon.sizePolicy().hasHeightForWidth())
        self.moveIcon.setSizePolicy(sizePolicy)
        self.moveIcon.setMinimumSize(QtCore.QSize(100, 100))
        self.moveIcon.setText("")
        self.moveIcon.setAutoDefault(False)
        self.moveIcon.setDefault(False)
        self.moveIcon.setFlat(True)
        self.moveIcon.setObjectName("moveIcon")
        self.horizontalLayout_24.addWidget(self.moveIcon)
        self.horizontalLayout_9.addWidget(self.frame)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMinimumSize(QtCore.QSize(80, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_17.addWidget(self.label_10)
        self.moveName = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveName.sizePolicy().hasHeightForWidth())
        self.moveName.setSizePolicy(sizePolicy)
        self.moveName.setObjectName("moveName")
        self.horizontalLayout_17.addWidget(self.moveName)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setMinimumSize(QtCore.QSize(80, 0))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_18.addWidget(self.label_11)
        self.moveCrit = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveCrit.sizePolicy().hasHeightForWidth())
        self.moveCrit.setSizePolicy(sizePolicy)
        self.moveCrit.setMaximum(100)
        self.moveCrit.setObjectName("moveCrit")
        self.horizontalLayout_18.addWidget(self.moveCrit)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setMinimumSize(QtCore.QSize(80, 0))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_19.addWidget(self.label_12)
        self.moveMiss = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveMiss.sizePolicy().hasHeightForWidth())
        self.moveMiss.setSizePolicy(sizePolicy)
        self.moveMiss.setMaximum(100)
        self.moveMiss.setObjectName("moveMiss")
        self.horizontalLayout_19.addWidget(self.moveMiss)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_9.addLayout(self.verticalLayout_12)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.moveDesc = QtWidgets.QTextEdit(self.groupBox_9)
        self.moveDesc.setLineWidth(2)
        self.moveDesc.setObjectName("moveDesc")
        self.verticalLayout_20.addWidget(self.moveDesc)
        self.verticalLayout_14.addWidget(self.groupBox_9)
        self.horizontalLayout_20.addLayout(self.verticalLayout_14)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.moveStats = QtWidgets.QTableWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveStats.sizePolicy().hasHeightForWidth())
        self.moveStats.setSizePolicy(sizePolicy)
        self.moveStats.setGridStyle(QtCore.Qt.SolidLine)
        self.moveStats.setObjectName("moveStats")
        self.moveStats.setColumnCount(1)
        self.moveStats.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(5, 0, item)
        self.moveStats.horizontalHeader().setVisible(False)
        self.moveStats.horizontalHeader().setCascadingSectionResizes(True)
        self.moveStats.horizontalHeader().setHighlightSections(False)
        self.moveStats.horizontalHeader().setSortIndicatorShown(False)
        self.moveStats.horizontalHeader().setStretchLastSection(True)
        self.moveStats.verticalHeader().setVisible(False)
        self.moveStats.verticalHeader().setCascadingSectionResizes(False)
        self.moveStats.verticalHeader().setDefaultSectionSize(24)
        self.moveStats.verticalHeader().setHighlightSections(True)
        self.moveStats.verticalHeader().setSortIndicatorShown(True)
        self.moveStats.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_7.addWidget(self.moveStats)
        self.horizontalLayout_20.addWidget(self.groupBox_5)
        self.horizontalLayout_20.setStretch(0, 1)
        self.moveLayout.addLayout(self.horizontalLayout_20)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.componentList = QtWidgets.QTreeWidget(self.tab)
        self.componentList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.componentList.setObjectName("componentList")
        item_0 = QtWidgets.QTreeWidgetItem(self.componentList)
        item_0.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.componentList)
        item_0.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.componentList)
        item_0.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.componentList.header().setDefaultSectionSize(500)
        self.componentList.header().setMinimumSectionSize(100)
        self.componentList.header().setStretchLastSection(True)
        self.verticalLayout_15.addWidget(self.componentList)
        self.moveLayout.addLayout(self.verticalLayout_15)
        self.horizontalLayout_16.addLayout(self.moveLayout)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.moveList = QtWidgets.QListWidget(self.tab)
        self.moveList.setObjectName("moveList")
        self.verticalLayout_9.addWidget(self.moveList)
        self.newMove = QtWidgets.QPushButton(self.tab)
        self.newMove.setObjectName("newMove")
        self.verticalLayout_9.addWidget(self.newMove)
        self.horizontalLayout_16.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionAdd_Floor = QtWidgets.QAction(MainWindow)
        self.actionAdd_Floor.setObjectName("actionAdd_Floor")
        self.actionAdd_Rare_Item_Attribute = QtWidgets.QAction(MainWindow)
        self.actionAdd_Rare_Item_Attribute.setObjectName("actionAdd_Rare_Item_Attribute")
        self.actionAdd_Skill = QtWidgets.QAction(MainWindow)
        self.actionAdd_Skill.setObjectName("actionAdd_Skill")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAdd_Attribute = QtWidgets.QAction(MainWindow)
        self.actionAdd_Attribute.setObjectName("actionAdd_Attribute")
        self.actionAdd_Effect = QtWidgets.QAction(MainWindow)
        self.actionAdd_Effect.setObjectName("actionAdd_Effect")
        self.actionAdd_Legendary_Item_Attribute = QtWidgets.QAction(MainWindow)
        self.actionAdd_Legendary_Item_Attribute.setObjectName("actionAdd_Legendary_Item_Attribute")
        self.actionAdd_Unique_Item_Attribute = QtWidgets.QAction(MainWindow)
        self.actionAdd_Unique_Item_Attribute.setObjectName("actionAdd_Unique_Item_Attribute")
        self.actionAdd_Monster_Attribute = QtWidgets.QAction(MainWindow)
        self.actionAdd_Monster_Attribute.setObjectName("actionAdd_Monster_Attribute")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAdd_Floor)
        self.menuEdit.addAction(self.actionAdd_Rare_Item_Attribute)
        self.menuEdit.addAction(self.actionAdd_Legendary_Item_Attribute)
        self.menuEdit.addAction(self.actionAdd_Unique_Item_Attribute)
        self.menuEdit.addAction(self.actionAdd_Monster_Attribute)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RPG Editor"))
        self.newDrop.setText(_translate("MainWindow", "Add New Drop..."))
        self.groupBox.setTitle(_translate("MainWindow", "Monster"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Rating"))
        self.label_2.setText(_translate("MainWindow", "Floor Type"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Stats"))
        item = self.monsterStats.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Attack"))
        item = self.monsterStats.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Speed"))
        item = self.monsterStats.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Defense"))
        item = self.monsterStats.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Health"))
        item = self.monsterStats.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Magic"))
        item = self.monsterStats.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resist"))
        item = self.monsterStats.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.monsterStats.isSortingEnabled()
        self.monsterStats.setSortingEnabled(False)
        item = self.monsterStats.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.monsterStats.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.monsterStats.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.monsterStats.item(3, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.monsterStats.item(4, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.monsterStats.item(5, 0)
        item.setText(_translate("MainWindow", "0"))
        self.monsterStats.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("MainWindow", "Attribute"))
        self.newAttribute.setText(_translate("MainWindow", "Add New Attribute..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Abilities"))
        self.newAbility.setText(_translate("MainWindow", "Add New Ability..."))
        self.newMonster.setText(_translate("MainWindow", "Create New Monster..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.monster_tab), _translate("MainWindow", "Monster"))
        self.label_5.setText(_translate("MainWindow", "Name"))
        self.dialogues.headerItem().setText(0, _translate("MainWindow", "Dialogues"))
        self.newDialogue.setText(_translate("MainWindow", "Add New Dialogue..."))
        self.events.headerItem().setText(0, _translate("MainWindow", "Events"))
        self.newEvent.setText(_translate("MainWindow", "Add New Event..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scenario_tab), _translate("MainWindow", "Events"))
        self.base.setText(_translate("MainWindow", "Base Item"))
        self.nonbase.setText(_translate("MainWindow", "Static Item"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_9.setText(_translate("MainWindow", "Item Type"))
        self.itemType.setItemText(0, _translate("MainWindow", "Sword"))
        self.itemType.setItemText(1, _translate("MainWindow", "Shield"))
        self.itemType.setItemText(2, _translate("MainWindow", "Wand"))
        self.itemType.setItemText(3, _translate("MainWindow", "Axe"))
        self.itemType.setItemText(4, _translate("MainWindow", "Helmet"))
        self.itemType.setItemText(5, _translate("MainWindow", "Legs"))
        self.itemType.setItemText(6, _translate("MainWindow", "Gloves"))
        self.itemType.setItemText(7, _translate("MainWindow", "Chest"))
        self.itemType.setItemText(8, _translate("MainWindow", "Ring"))
        self.itemType.setItemText(9, _translate("MainWindow", "Shoes"))
        self.itemType.setItemText(10, _translate("MainWindow", "Boots"))
        self.itemType.setItemText(11, _translate("MainWindow", "Necklace"))
        self.itemType.setItemText(12, _translate("MainWindow", "Mace"))
        self.itemType.setItemText(13, _translate("MainWindow", "Staff"))
        self.label_8.setText(_translate("MainWindow", "Slot"))
        self.itemSlot.setItemText(0, _translate("MainWindow", "Hand"))
        self.itemSlot.setItemText(1, _translate("MainWindow", "Body"))
        self.itemSlot.setItemText(2, _translate("MainWindow", "Legs"))
        self.itemSlot.setItemText(3, _translate("MainWindow", "Feet"))
        self.itemSlot.setItemText(4, _translate("MainWindow", "Head"))
        self.itemSlot.setItemText(5, _translate("MainWindow", "Extra"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Stats"))
        item = self.itemStats.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Attack"))
        item = self.itemStats.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Speed"))
        item = self.itemStats.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Defense"))
        item = self.itemStats.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Health"))
        item = self.itemStats.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Magic"))
        item = self.itemStats.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resist"))
        item = self.itemStats.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Action"))
        item = self.itemStats.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.itemStats.isSortingEnabled()
        self.itemStats.setSortingEnabled(False)
        item = self.itemStats.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(3, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(4, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(5, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(6, 0)
        item.setText(_translate("MainWindow", "0"))
        self.itemStats.setSortingEnabled(__sortingEnabled)
        self.groupBox_8.setTitle(_translate("MainWindow", "Attributes"))
        self.attrButton.setText(_translate("MainWindow", "Add New Attribute..."))
        self.pushButton_6.setText(_translate("MainWindow", "Add New Item..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.item_tab), _translate("MainWindow", "Item"))
        self.label_10.setText(_translate("MainWindow", "Name"))
        self.label_11.setText(_translate("MainWindow", "Critical Chance"))
        self.label_12.setText(_translate("MainWindow", "Miss Chance"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Description"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Stat Distribution"))
        item = self.moveStats.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Attack"))
        item = self.moveStats.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Speed"))
        item = self.moveStats.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Defense"))
        item = self.moveStats.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Health"))
        item = self.moveStats.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Magic"))
        item = self.moveStats.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resist"))
        item = self.moveStats.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.moveStats.isSortingEnabled()
        self.moveStats.setSortingEnabled(False)
        item = self.moveStats.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.moveStats.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.moveStats.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.moveStats.item(3, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.moveStats.item(4, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.moveStats.item(5, 0)
        item.setText(_translate("MainWindow", "0"))
        self.moveStats.setSortingEnabled(__sortingEnabled)
        self.componentList.headerItem().setText(0, _translate("MainWindow", "Components"))
        __sortingEnabled = self.componentList.isSortingEnabled()
        self.componentList.setSortingEnabled(False)
        self.componentList.topLevelItem(0).setText(0, _translate("MainWindow", "<Components>"))
        self.componentList.topLevelItem(1).setText(0, _translate("MainWindow", "<MissComponents>"))
        self.componentList.topLevelItem(2).setText(0, _translate("MainWindow", "<CritComponents>"))
        self.componentList.setSortingEnabled(__sortingEnabled)
        self.newMove.setText(_translate("MainWindow", "Add New Move..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Moves"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAdd_Floor.setText(_translate("MainWindow", "Add Floor Type..."))
        self.actionAdd_Rare_Item_Attribute.setText(_translate("MainWindow", "Add Rare Item Attribute..."))
        self.actionAdd_Skill.setText(_translate("MainWindow", "Add Skill..."))
        self.actionQuit.setText(_translate("MainWindow", "Update"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAdd_Attribute.setText(_translate("MainWindow", "Add Attribute..."))
        self.actionAdd_Effect.setText(_translate("MainWindow", "Add Effect..."))
        self.actionAdd_Legendary_Item_Attribute.setText(_translate("MainWindow", "Add Legendary Item Attribute..."))
        self.actionAdd_Unique_Item_Attribute.setText(_translate("MainWindow", "Add Unique Item Attribute"))
        self.actionAdd_Monster_Attribute.setText(_translate("MainWindow", "Add Monster Attribute..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

