# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\editor.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.monster_tab = QtWidgets.QWidget()
        self.monster_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.monster_tab.setObjectName("monster_tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.monster_tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.monster_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_3.addWidget(self.graphicsView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_2 = QtWidgets.QListWidget(self.monster_tab)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout.addWidget(self.listWidget_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.monster_tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.monster_tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(24)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_7.addWidget(self.listWidget_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_7.addWidget(self.pushButton_4)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listView_2 = QtWidgets.QListView(self.groupBox_3)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_4.addWidget(self.listView_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.monster_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_5.addWidget(self.listWidget)
        self.pushButton = QtWidgets.QPushButton(self.monster_tab)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.monster_tab, "")
        self.scenario_tab = QtWidgets.QWidget()
        self.scenario_tab.setObjectName("scenario_tab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.scenario_tab)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.dialogueLayout = QtWidgets.QVBoxLayout()
        self.dialogueLayout.setObjectName("dialogueLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.eventName = QtWidgets.QLineEdit(self.scenario_tab)
        self.eventName.setObjectName("eventName")
        self.horizontalLayout_10.addWidget(self.eventName)
        self.dialogueLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.eventFloorType = QtWidgets.QComboBox(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventFloorType.sizePolicy().hasHeightForWidth())
        self.eventFloorType.setSizePolicy(sizePolicy)
        self.eventFloorType.setObjectName("eventFloorType")
        self.horizontalLayout_11.addWidget(self.eventFloorType)
        self.dialogueLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.eventRoomType = QtWidgets.QComboBox(self.scenario_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventRoomType.sizePolicy().hasHeightForWidth())
        self.eventRoomType.setSizePolicy(sizePolicy)
        self.eventRoomType.setObjectName("eventRoomType")
        self.eventRoomType.addItem("")
        self.eventRoomType.addItem("")
        self.eventRoomType.addItem("")
        self.eventRoomType.addItem("")
        self.horizontalLayout_12.addWidget(self.eventRoomType)
        self.dialogueLayout.addLayout(self.horizontalLayout_12)
        self.dialogueList = QtWidgets.QListWidget(self.scenario_tab)
        self.dialogueList.setObjectName("dialogueList")
        self.dialogueLayout.addWidget(self.dialogueList)
        self.newDialogue = QtWidgets.QPushButton(self.scenario_tab)
        self.newDialogue.setObjectName("newDialogue")
        self.dialogueLayout.addWidget(self.newDialogue)
        self.horizontalLayout_13.addLayout(self.dialogueLayout)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.eventList = QtWidgets.QListWidget(self.scenario_tab)
        self.eventList.setBatchSize(100)
        self.eventList.setSelectionRectVisible(False)
        self.eventList.setObjectName("eventList")
        self.verticalLayout_13.addWidget(self.eventList)
        self.newEvent = QtWidgets.QPushButton(self.scenario_tab)
        self.newEvent.setObjectName("newEvent")
        self.verticalLayout_13.addWidget(self.newEvent)
        self.horizontalLayout_13.addLayout(self.verticalLayout_13)
        self.horizontalLayout_13.setStretch(0, 1)
        self.tabWidget.addTab(self.scenario_tab, "")
        self.item_tab = QtWidgets.QWidget()
        self.item_tab.setObjectName("item_tab")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.item_tab)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.itemBox = QtWidgets.QVBoxLayout()
        self.itemBox.setObjectName("itemBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.itemBase = QtWidgets.QHBoxLayout()
        self.itemBase.setObjectName("itemBase")
        self.base = QtWidgets.QRadioButton(self.item_tab)
        self.base.setChecked(True)
        self.base.setObjectName("base")
        self.itemBase.addWidget(self.base)
        self.nonbase = QtWidgets.QRadioButton(self.item_tab)
        self.nonbase.setObjectName("nonbase")
        self.itemBase.addWidget(self.nonbase)
        self.verticalLayout_8.addLayout(self.itemBase)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.item_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.itemName = QtWidgets.QLineEdit(self.item_tab)
        self.itemName.setObjectName("itemName")
        self.horizontalLayout_6.addWidget(self.itemName)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.item_tab)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        self.itemType = QtWidgets.QComboBox(self.item_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemType.sizePolicy().hasHeightForWidth())
        self.itemType.setSizePolicy(sizePolicy)
        self.itemType.setObjectName("itemType")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.horizontalLayout_15.addWidget(self.itemType)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.item_tab)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.itemSlot = QtWidgets.QComboBox(self.item_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemSlot.sizePolicy().hasHeightForWidth())
        self.itemSlot.setSizePolicy(sizePolicy)
        self.itemSlot.setObjectName("itemSlot")
        self.itemSlot.addItem("")
        self.itemSlot.addItem("")
        self.itemSlot.addItem("")
        self.itemSlot.addItem("")
        self.itemSlot.addItem("")
        self.itemSlot.addItem("")
        self.horizontalLayout_14.addWidget(self.itemSlot)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.itemBox.addLayout(self.verticalLayout_8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.item_tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.itemStats = QtWidgets.QTableWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemStats.sizePolicy().hasHeightForWidth())
        self.itemStats.setSizePolicy(sizePolicy)
        self.itemStats.setGridStyle(QtCore.Qt.SolidLine)
        self.itemStats.setObjectName("itemStats")
        self.itemStats.setColumnCount(1)
        self.itemStats.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemStats.setItem(6, 0, item)
        self.itemStats.horizontalHeader().setVisible(False)
        self.itemStats.horizontalHeader().setCascadingSectionResizes(True)
        self.itemStats.horizontalHeader().setHighlightSections(False)
        self.itemStats.horizontalHeader().setSortIndicatorShown(False)
        self.itemStats.horizontalHeader().setStretchLastSection(True)
        self.itemStats.verticalHeader().setVisible(False)
        self.itemStats.verticalHeader().setCascadingSectionResizes(False)
        self.itemStats.verticalHeader().setDefaultSectionSize(24)
        self.itemStats.verticalHeader().setHighlightSections(True)
        self.itemStats.verticalHeader().setSortIndicatorShown(True)
        self.itemStats.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_10.addWidget(self.itemStats)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.item_tab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.attrList = QtWidgets.QListWidget(self.groupBox_8)
        self.attrList.setObjectName("attrList")
        self.verticalLayout_11.addWidget(self.attrList)
        self.attrButton = QtWidgets.QPushButton(self.groupBox_8)
        self.attrButton.setObjectName("attrButton")
        self.verticalLayout_11.addWidget(self.attrButton)
        self.horizontalLayout_8.addWidget(self.groupBox_8)
        self.itemBox.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_22.addLayout(self.itemBox)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.itemList = QtWidgets.QListWidget(self.item_tab)
        self.itemList.setObjectName("itemList")
        self.verticalLayout_22.addWidget(self.itemList)
        self.pushButton_6 = QtWidgets.QPushButton(self.item_tab)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_22.addWidget(self.pushButton_6)
        self.horizontalLayout_22.addLayout(self.verticalLayout_22)
        self.tabWidget.addTab(self.item_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.moveIcon = QtWidgets.QPushButton(self.frame)
        self.moveIcon.setMinimumSize(QtCore.QSize(100, 100))
        self.moveIcon.setText("")
        self.moveIcon.setAutoDefault(False)
        self.moveIcon.setDefault(False)
        self.moveIcon.setFlat(True)
        self.moveIcon.setObjectName("moveIcon")
        self.horizontalLayout_24.addWidget(self.moveIcon)
        self.horizontalLayout_9.addWidget(self.frame)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMinimumSize(QtCore.QSize(80, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_17.addWidget(self.label_10)
        self.moveName = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveName.sizePolicy().hasHeightForWidth())
        self.moveName.setSizePolicy(sizePolicy)
        self.moveName.setObjectName("moveName")
        self.horizontalLayout_17.addWidget(self.moveName)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setMinimumSize(QtCore.QSize(80, 0))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_18.addWidget(self.label_11)
        self.moveCrit = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveCrit.sizePolicy().hasHeightForWidth())
        self.moveCrit.setSizePolicy(sizePolicy)
        self.moveCrit.setMaximum(100)
        self.moveCrit.setObjectName("moveCrit")
        self.horizontalLayout_18.addWidget(self.moveCrit)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setMinimumSize(QtCore.QSize(80, 0))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_19.addWidget(self.label_12)
        self.moveMiss = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveMiss.sizePolicy().hasHeightForWidth())
        self.moveMiss.setSizePolicy(sizePolicy)
        self.moveMiss.setMaximum(100)
        self.moveMiss.setObjectName("moveMiss")
        self.horizontalLayout_19.addWidget(self.moveMiss)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_9.addLayout(self.verticalLayout_12)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.moveDesc = QtWidgets.QTextEdit(self.groupBox_9)
        self.moveDesc.setLineWidth(2)
        self.moveDesc.setObjectName("moveDesc")
        self.verticalLayout_20.addWidget(self.moveDesc)
        self.verticalLayout_14.addWidget(self.groupBox_9)
        self.horizontalLayout_20.addLayout(self.verticalLayout_14)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.moveStats = QtWidgets.QTableWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveStats.sizePolicy().hasHeightForWidth())
        self.moveStats.setSizePolicy(sizePolicy)
        self.moveStats.setGridStyle(QtCore.Qt.SolidLine)
        self.moveStats.setObjectName("moveStats")
        self.moveStats.setColumnCount(1)
        self.moveStats.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moveStats.setItem(5, 0, item)
        self.moveStats.horizontalHeader().setVisible(False)
        self.moveStats.horizontalHeader().setCascadingSectionResizes(True)
        self.moveStats.horizontalHeader().setHighlightSections(False)
        self.moveStats.horizontalHeader().setSortIndicatorShown(False)
        self.moveStats.horizontalHeader().setStretchLastSection(True)
        self.moveStats.verticalHeader().setVisible(False)
        self.moveStats.verticalHeader().setCascadingSectionResizes(False)
        self.moveStats.verticalHeader().setDefaultSectionSize(24)
        self.moveStats.verticalHeader().setHighlightSections(True)
        self.moveStats.verticalHeader().setSortIndicatorShown(True)
        self.moveStats.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_7.addWidget(self.moveStats)
        self.horizontalLayout_20.addWidget(self.groupBox_5)
        self.horizontalLayout_20.setStretch(0, 1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.compList = QtWidgets.QListWidget(self.tab_2)
        self.compList.setObjectName("compList")
        self.horizontalLayout_16.addWidget(self.compList)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.critList = QtWidgets.QListWidget(self.tab_3)
        self.critList.setObjectName("critList")
        self.verticalLayout_19.addWidget(self.critList)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.missList = QtWidgets.QListWidget(self.tab_4)
        self.missList.setObjectName("missList")
        self.verticalLayout_18.addWidget(self.missList)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.verticalLayout_15.addWidget(self.tabWidget_2)
        self.newComponent = QtWidgets.QPushButton(self.tab)
        self.newComponent.setObjectName("newComponent")
        self.verticalLayout_15.addWidget(self.newComponent)
        self.horizontalLayout_21.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.modifierList = QtWidgets.QListWidget(self.tab)
        self.modifierList.setObjectName("modifierList")
        self.verticalLayout_16.addWidget(self.modifierList)
        self.newModifier = QtWidgets.QPushButton(self.tab)
        self.newModifier.setFlat(False)
        self.newModifier.setObjectName("newModifier")
        self.verticalLayout_16.addWidget(self.newModifier)
        self.horizontalLayout_21.addLayout(self.verticalLayout_16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_21)
        self.verticalLayout_17.setStretch(0, 1)
        self.horizontalLayout_23.addLayout(self.verticalLayout_17)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.moveList = QtWidgets.QListWidget(self.tab)
        self.moveList.setObjectName("moveList")
        self.verticalLayout_9.addWidget(self.moveList)
        self.newMove = QtWidgets.QPushButton(self.tab)
        self.newMove.setObjectName("newMove")
        self.verticalLayout_9.addWidget(self.newMove)
        self.horizontalLayout_23.addLayout(self.verticalLayout_9)
        self.horizontalLayout_23.setStretch(0, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionAdd_Floor_Type = QtWidgets.QAction(MainWindow)
        self.actionAdd_Floor_Type.setObjectName("actionAdd_Floor_Type")
        self.actionAdd_Item = QtWidgets.QAction(MainWindow)
        self.actionAdd_Item.setObjectName("actionAdd_Item")
        self.actionAdd_Skill = QtWidgets.QAction(MainWindow)
        self.actionAdd_Skill.setObjectName("actionAdd_Skill")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAdd_Attribute = QtWidgets.QAction(MainWindow)
        self.actionAdd_Attribute.setObjectName("actionAdd_Attribute")
        self.actionAdd_Effect = QtWidgets.QAction(MainWindow)
        self.actionAdd_Effect.setObjectName("actionAdd_Effect")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAdd_Floor_Type)
        self.menuEdit.addAction(self.actionAdd_Item)
        self.menuEdit.addAction(self.actionAdd_Skill)
        self.menuEdit.addAction(self.actionAdd_Attribute)
        self.menuEdit.addAction(self.actionAdd_Effect)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.eventList.setCurrentRow(-1)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RPG Editor"))
        self.pushButton_3.setText(_translate("MainWindow", "Add New Drop..."))
        self.groupBox.setTitle(_translate("MainWindow", "Monster"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Floor Type"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Stats"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Attack"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Speed"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Defense"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Health"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Magic"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resist"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("MainWindow", "Effects"))
        self.pushButton_4.setText(_translate("MainWindow", "Add New Effect..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Abilities"))
        self.pushButton_2.setText(_translate("MainWindow", "Add New Ability..."))
        self.pushButton.setText(_translate("MainWindow", "Create New Monster..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.monster_tab), _translate("MainWindow", "Monster"))
        self.label_5.setText(_translate("MainWindow", "Name"))
        self.label_6.setText(_translate("MainWindow", "Floor Type"))
        self.label_7.setText(_translate("MainWindow", "Room Type"))
        self.eventRoomType.setItemText(0, _translate("MainWindow", "Event"))
        self.eventRoomType.setItemText(1, _translate("MainWindow", "Entrance"))
        self.eventRoomType.setItemText(2, _translate("MainWindow", "Exit"))
        self.eventRoomType.setItemText(3, _translate("MainWindow", "Monster"))
        self.newDialogue.setText(_translate("MainWindow", "Add New Dialogue..."))
        self.newEvent.setText(_translate("MainWindow", "Add New Event..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scenario_tab), _translate("MainWindow", "Events"))
        self.base.setText(_translate("MainWindow", "Base Item"))
        self.nonbase.setText(_translate("MainWindow", "Static Item"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_9.setText(_translate("MainWindow", "Item Type"))
        self.itemType.setItemText(0, _translate("MainWindow", "Sword"))
        self.itemType.setItemText(1, _translate("MainWindow", "Shield"))
        self.itemType.setItemText(2, _translate("MainWindow", "Wand"))
        self.itemType.setItemText(3, _translate("MainWindow", "Axe"))
        self.itemType.setItemText(4, _translate("MainWindow", "Helmet"))
        self.itemType.setItemText(5, _translate("MainWindow", "Legs"))
        self.itemType.setItemText(6, _translate("MainWindow", "Gloves"))
        self.itemType.setItemText(7, _translate("MainWindow", "Chest"))
        self.itemType.setItemText(8, _translate("MainWindow", "Ring"))
        self.itemType.setItemText(9, _translate("MainWindow", "Shoes"))
        self.itemType.setItemText(10, _translate("MainWindow", "Boots"))
        self.itemType.setItemText(11, _translate("MainWindow", "Necklace"))
        self.itemType.setItemText(12, _translate("MainWindow", "Mace"))
        self.itemType.setItemText(13, _translate("MainWindow", "Staff"))
        self.label_8.setText(_translate("MainWindow", "Slot"))
        self.itemSlot.setItemText(0, _translate("MainWindow", "Hand"))
        self.itemSlot.setItemText(1, _translate("MainWindow", "Body"))
        self.itemSlot.setItemText(2, _translate("MainWindow", "Legs"))
        self.itemSlot.setItemText(3, _translate("MainWindow", "Feet"))
        self.itemSlot.setItemText(4, _translate("MainWindow", "Head"))
        self.itemSlot.setItemText(5, _translate("MainWindow", "Extra"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Stats"))
        item = self.itemStats.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Attack"))
        item = self.itemStats.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Speed"))
        item = self.itemStats.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Defense"))
        item = self.itemStats.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Health"))
        item = self.itemStats.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Magic"))
        item = self.itemStats.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resist"))
        item = self.itemStats.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Action"))
        item = self.itemStats.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.itemStats.isSortingEnabled()
        self.itemStats.setSortingEnabled(False)
        item = self.itemStats.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(3, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(4, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(5, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.itemStats.item(6, 0)
        item.setText(_translate("MainWindow", "0"))
        self.itemStats.setSortingEnabled(__sortingEnabled)
        self.groupBox_8.setTitle(_translate("MainWindow", "Attributes"))
        self.attrButton.setText(_translate("MainWindow", "Add New Attribute..."))
        self.pushButton_6.setText(_translate("MainWindow", "Add New Item..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.item_tab), _translate("MainWindow", "Item"))
        self.label_10.setText(_translate("MainWindow", "Name"))
        self.label_11.setText(_translate("MainWindow", "Critical Chance"))
        self.label_12.setText(_translate("MainWindow", "Miss Chance"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Description"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Stat Distribution"))
        item = self.moveStats.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Attack"))
        item = self.moveStats.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Speed"))
        item = self.moveStats.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Defense"))
        item = self.moveStats.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Health"))
        item = self.moveStats.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Magic"))
        item = self.moveStats.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resist"))
        item = self.moveStats.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.moveStats.isSortingEnabled()
        self.moveStats.setSortingEnabled(False)
        item = self.moveStats.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.moveStats.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.moveStats.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.moveStats.item(3, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.moveStats.item(4, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.moveStats.item(5, 0)
        item.setText(_translate("MainWindow", "0"))
        self.moveStats.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Standard"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Critical"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Miss"))
        self.newComponent.setText(_translate("MainWindow", "Add New Component..."))
        self.newModifier.setText(_translate("MainWindow", "Add New Modifier..."))
        self.newMove.setText(_translate("MainWindow", "Add New Move..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Moves"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAdd_Floor_Type.setText(_translate("MainWindow", "Add Floor Type..."))
        self.actionAdd_Item.setText(_translate("MainWindow", "Add Item..."))
        self.actionAdd_Skill.setText(_translate("MainWindow", "Add Skill..."))
        self.actionQuit.setText(_translate("MainWindow", "Update"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAdd_Attribute.setText(_translate("MainWindow", "Add Attribute..."))
        self.actionAdd_Effect.setText(_translate("MainWindow", "Add Effect..."))

